modLoader = "javafml"
loaderVersion = "[38,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "fofr"
version = "${version}"
displayName = "Forge of Fiends (Redux)"
authors = "PhoenixVX, wolverbyte"
description = '''
'''
#logoFile = ""

[[dependencies.fofr]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fofr]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fofr]]
modId = "architectury"
mandatory = true
versionRange = "[3.2.57,)"
ordering = "AFTER"
side = "BOTH"